name: Dart CI

on:
  push:
    branches:
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter

    steps:
    - uses: actions/checkout@v1
    - name: setHome
      run: export HOME='/home/cirrus'
    - name: Install dependencies
      run: sudo /home/cirrus/sdks/flutter/bin/flutter pub get
    - name: build
      run: flutter build apk --target-platform android-arm64 --split-per-abi

    - name: console log
      run:  cat /tmp/flutter_01.log
