name: Dart CI

on:
  push:
    branches:
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: flutter pub get
    - name: build 
      run: flutter build apk --target-platform android-arm64 --split-per-abi
